name: flurec
description: A simple audio recorder made with Flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  auto_size_text: ^3.0.0-nullsafety.0
  permission_handler: ^8.1.4+2
  shared_preferences: ^2.0.6
  path_provider: ^2.0.2
  flutter_sound: ^8.3.9
  share: ^2.0.4
  filesize: ^2.0.1
  wakelock: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true